data<-read.table("household_power_consumption.txt",header = TRUE,sep = ";",stringsAsFactors = FALSE)
data$Date<-as.Date(data$Date,format = "%d/%m/%Y")
data<-data[data$Date=="2007-02-01"|data$Date=="2007-02-02",]
xday<-paste(data$Date,data$Time,sep = " ")
l<-strptime(xday,"%Y-%m-%d %H:%M:%S")
data<-cbind("Date_and_Time"=l,data)
data[3:9]<-sapply(data[3:9],as.numeric)
plot(data$Date_and_Time,data$Sub_metering_1,type = "n",xlab="Date and Time",ylab="Energy Sub Metering")
lines(data$Date_and_Time,data$Sub_metering_1)
lines(data$Date_and_Time,data$Sub_metering_2,col = "red")
lines(data$Date_and_Time,data$Sub_metering_3,col = "blue")
legend("topright",pch = c("-","-","-"),col=c("black","red","blue"),legend = c("sub_metering_1","sub_metering_2","sub_metering_3"))
dev.copy(png,file = "plot3.png")
dev.off()