data<-read.table("household_power_consumption.txt",header = TRUE,sep = ";",stringsAsFactors = FALSE)
data$Date<-as.Date(data$Date,format = "%d/%m/%Y")
data<-data[data$Date=="2007-02-01"|data$Date=="2007-02-02",]
xday<-paste(data$Date,data$Time,sep = " ")
l<-strptime(xday,"%Y-%m-%d %H:%M:%S")
data<-cbind("Date_and_Time"=l,data)
data[4:10]<-sapply(data[4:10],as.numeric)
png(filename = "plot4.png")
par(mfrow=c(2,2))
plot(data$Date_and_Time,data$Global_active_power,type = "n",xlab = "Date and Time",ylab = "Global active power(Kilo Watts)")
lines(data$Date_and_Time,data$Global_active_power)
with(data,plot(Date_and_Time,Voltage,xlab="date and time",ylab = "Global Reactive Power(Kilo watts)",type = "n"))
lines(data$Date_and_Time,data$Voltage)
plot(data$Date_and_Time,data$Sub_metering_1,type = "n",xlab="Date and Time",ylab="Energy Sub Metering")
lines(data$Date_and_Time,data$Sub_metering_1)
lines(data$Date_and_Time,data$Sub_metering_2,col = "red")
lines(data$Date_and_Time,data$Sub_metering_3,col = "blue")
legend("topright",pch = c("-","-","-"),col=c("black","red","blue"),legend = c("sub_metering_1","sub_metering_2","sub_metering_3"))
with(data,plot(Date_and_Time,Global_reactive_power,xlab="date and time",ylab = "Global Reactive Power(Kilo watts)",type = "n"))
lines(data$Date_and_Time,data$Global_reactive_power)
dev.off()
